######################################
### Tests for candidates Api #########
######################################



### Get all candidates ###
GET http://tkdclub.local/api/index.php/v1/tkdclub/candidates HTTP/1.1
Authorization: Basic admin:admin
Accept: application/vnd.api+json


### Get specific candidate id 1 ###
GET http://tkdclub.local/api/index.php/v1/tkdclub/candidates/4 HTTP/1.1
Authorization: Basic admin:admin
Accept: application/vnd.api+json