CREATE TABLE IF NOT EXISTS `#__tkdclub_members` (
  `member_id` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(50) NOT NULL,
  `lastname` varchar(50) NOT NULL,
  `birthdate` date NOT NULL,
  `sex` varchar(10) NOT NULL,
  `citizenship` varchar(10) NOT NULL DEFAULT '',
  `street` varchar(50) NOT NULL DEFAULT '',
  `zip` varchar(10) NOT NULL DEFAULT '',
  `city` varchar(50) NOT NULL DEFAULT '',
  `country` varchar(50) NOT NULL DEFAULT '',
  `phone` varchar(50) NOT NULL DEFAULT '',
  `email` varchar(100) NOT NULL DEFAULT '',
  `iban` varchar(50) NOT NULL DEFAULT '',
  `notes_personel` text,
  `memberpass` varchar(30) DEFAULT NULL,
  `grade` varchar(30) NOT NULL DEFAULT '',
  `lastpromotion` date DEFAULT NULL,
  `licenses` text,
  `notes_taekwondo` text,
  `functions` text,
  `entry` date DEFAULT NULL,
  `leave` date DEFAULT NULL,
  `member_state` varchar(10) NOT NULL DEFAULT 'active',
  `notes_clubdata` text,
  `attachments` text,
  `image` varchar(255)  DEFAULT NULL,
  `user_id` int(11) NOT NULL DEFAULT '0',
  `created` datetime DEFAULT NULL,
  `created_by` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `modified` datetime DEFAULT NULL,
  `modified_by` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `checked_out` int(10) UNSIGNED DEFAULT NULL,
  `checked_out_time` datetime DEFAULT NULL,
  PRIMARY KEY (`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__tkdclub_trainings` (
  `training_id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `trainer` int(5) NOT NULL,
  `km_trainer` int(4) NOT NULL,
  `trainer_paid` tinyint(3) NOT NULL DEFAULT 0,
  `assist1` int(5) DEFAULT NULL,
  `km_assist1` int(4) DEFAULT NULL, 
  `assist1_paid` tinyint(3) DEFAULT NULL,
  `assist2` int(5) DEFAULT NULL,
  `km_assist2` int(4) DEFAULT NULL,
  `assist2_paid` tinyint(3) DEFAULT NULL,
  `assist3` int(5) DEFAULT NULL,
  `km_assist3` int(4) DEFAULT NULL,
  `assist3_paid` tinyint(3) DEFAULT NULL,
  `type` varchar(50) NOT NULL,
  `participants` int(5) NOT NULL,
  `notes` text,
  `payment_state` tinyint(3) NOT NULL DEFAULT 0,
  `created` DATETIME DEFAULT NULL,
  `created_by` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `modified` datetime DEFAULT NULL,
  `modified_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) UNSIGNED DEFAULT NULL,
  `checked_out_time` datetime DEFAULT NULL,
  PRIMARY KEY (`training_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

/*
CREATE TABLE IF NOT EXISTS `#__tkdclub_medals` (
  `medal_id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `championship` varchar(50) NOT NULL,
  `type` varchar(50) NOT NULL, 
  `class` varchar(50) NOT NULL,
  `placing` tinyint(11) NOT NULL,
  `winner_ids` varchar(50) NOT NULL,
  `notes` text NOT NULL,
  `state` tinyint(3) NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  PRIMARY KEY (`medal_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__tkdclub_promotions` (
  `promotion_id` int(10) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `city` varchar(20) NOT NULL,
  `type` varchar(20) NOT NULL,
  `examiner_name` varchar(50),
  `examiner_address` varchar(50) NOT NULL,
  `examiner_email` varchar(50) NOT NULL,
  `promotion_state` tinyint(4) NOT NULL,
  `notes` text NOT NULL,
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  PRIMARY KEY (`promotion_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__tkdclub_candidates` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `id_promotion` int(10) NOT NULL,
  `id_candidate` int(10) NOT NULL,
  `grade_achieve` varchar(20) NOT NULL,
  `test_state` tinyint(4) NOT NULL,
  `notes` text NOT NULL,
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__tkdclub_events` (
  `event_id` int(10) NOT NULL AUTO_INCREMENT,
  `title` text NOT NULL,
  `date` date NOT NULL DEFAULT '0000-00-00',
  `deadline` date NOT NULL DEFAULT '0000-00-00',
  `min` int(11) NOT NULL,
  `max` int(11) NOT NULL,
  `published` tinyint(1) NOT NULL,
  `notes` text NOT NULL,
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  PRIMARY KEY (`event_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__tkdclub_event_participants` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `event_id` int(11) NOT NULL,
  `firstname` varchar(50) NOT NULL,
  `lastname` varchar(50) NOT NULL,
  `clubname` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `registered` INT(3) NOT NULL,
  `grade` varchar(30) NOT NULL,
  `age` TINYTEXT NOT NULL,
  `notes` text NOT NULL,
  `user1` varchar(50) NOT NULL,
  `user2` varchar(50) NOT NULL,
  `user3` varchar(50) NOT NULL,
  `user4` varchar(50) NOT NULL,
  `store_data` tinyint(4) NOT NULL,
  `privacy_agreed` tinyint(4) NOT NULL,
  `published` tinyint(4) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__tkdclub_newsletter_subscribers` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(50) NOT NULL,
  `lastname` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `origin` varchar(10) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  PRIMARY KEY (`id`)
 ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci; */