CREATE TABLE IF NOT EXISTS `#__tkdclub_members` (
  `member_id` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(50) NOT NULL,
  `lastname` varchar(50) NOT NULL,
  `birthdate` date NOT NULL DEFAULT '0000-00-00',
  `sex` varchar(10) NOT NULL,
  `citizenship` varchar(10) NOT NULL,
  `street` varchar(50) NOT NULL,
  `zip` varchar(10) NOT NULL,
  `city` varchar(50) NOT NULL,
  `country` varchar(50) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `notes_personel` text NOT NULL,
  `memberpass` int(10) NOT NULL,
  `grade` varchar(30) NOT NULL,
  `lastpromotion` date NOT NULL DEFAULT '0000-00-00',
  `notes_taekwondo` text NOT NULL,
  `functions` text NOT NULL,
  `entry` date NOT NULL DEFAULT '0000-00-00',
  `leave` date NOT NULL DEFAULT '0000-00-00',
  `member_state` varchar(10) NOT NULL,
  `notes_clubdata` text NOT NULL,
  `attachments` TINYINT(1) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` INT(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) unsigned NOT NULL,
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`member_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;